-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 11:05:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Brainiac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Brainiac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Brainiac` (
  `Username` VARCHAR(20) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `LastLogin` DATETIME NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `PostID` INT NOT NULL,
  `Message` TEXT(1000) NOT NULL,
  `DateCreated` DATETIME NOT NULL,
  `DateModified` DATETIME NULL,
  `Brainiac_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`PostID`),
  INDEX `fk_Post_Brainiac_idx` (`Brainiac_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Brainiac`
    FOREIGN KEY (`Brainiac_Username`)
    REFERENCES `mydb`.`Brainiac` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Friend` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Friend` (
  `Username` VARCHAR(20) NOT NULL,
  `FriendType` VARCHAR(45) NOT NULL,
  `DateConnected` DATETIME NOT NULL,
  `Brainiac_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Username`),
  INDEX `fk_Friend_Brainiac1_idx` (`Brainiac_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Friend_Brainiac1`
    FOREIGN KEY (`Brainiac_Username`)
    REFERENCES `mydb`.`Brainiac` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Follower`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Follower` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Follower` (
  `Username` VARCHAR(20) NOT NULL,
  `DateFollowed` DATETIME NOT NULL,
  `Brainiac_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Username`),
  INDEX `fk_Follower_Brainiac1_idx` (`Brainiac_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Follower_Brainiac1`
    FOREIGN KEY (`Brainiac_Username`)
    REFERENCES `mydb`.`Brainiac` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DirectMessage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DirectMessage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DirectMessage` (
  `BrainiacUsername` VARCHAR(20) NOT NULL,
  `FriendUsername` VARCHAR(20) NOT NULL,
  `Message` TEXT(1000) NOT NULL,
  `DateSent` DATETIME NOT NULL,
  `DateModified` DATETIME NULL,
  PRIMARY KEY (`BrainiacUsername`, `FriendUsername`),
  INDEX `fk_Brainiac_has_Friend_Friend1_idx` (`FriendUsername` ASC) VISIBLE,
  INDEX `fk_Brainiac_has_Friend_Brainiac1_idx` (`BrainiacUsername` ASC) VISIBLE,
  CONSTRAINT `fk_Brainiac_has_Friend_Brainiac1`
    FOREIGN KEY (`BrainiacUsername`)
    REFERENCES `mydb`.`Brainiac` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Brainiac_has_Friend_Friend1`
    FOREIGN KEY (`FriendUsername`)
    REFERENCES `mydb`.`Friend` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
